name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        project:
          - BIDS.Parser.Tests
          - BIDS.Parser.Variable.Tests
        os:
          - ubuntu-latest
        dotnet-version:
          - '6.0.x'
        framework:
          - net6.0
        include:
          - project: BIDS.Parser.Variable.Tests
            os: ubuntu-latest
            dotnet-version: '3.1.x'
            framework: netcoreapp3.1
          - project: BIDS.Parser.Variable.Tests
            os: ubuntu-latest
            dotnet-version: '2.1.x'
            framework: netcoreapp2.1
          - project: BIDS.Parser.Variable.Tests
            os: windows-latest
            dotnet-version: '6.0.x'
            framework: net48

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore ${{ matrix.project }} -nowarn:NETSDK1138

      - name: Build ${{ matrix.project }}
        run: dotnet build ${{ matrix.project }} -c Release --no-restore -f ${{ matrix.framework }} -nowarn:NETSDK1138
      - name: Test ${{ matrix.project }}
        run: dotnet test ${{ matrix.project }} -c Release --no-build -v normal -f ${{ matrix.framework }}
